import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';


import "../globals.css";
import TopBar from "../components/shared/TopBar";
import MainBox from "../components/shared/Main Box";
import LeftBar from "../components/shared/LeftBar";
import Bottombar from "../components/shared/BottomBar";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EZ Reality",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <LeftBar />
          <main>
            <TopBar />
            <MainBox />
            <Bottombar />
            {children}
          </main>
      </body>
    </html>
  </ClerkProvider>
  );
}
