import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark, shadesOfPurple  } from "@clerk/themes";


import "../globals.css";
import TopBar from "../components/shared/TopBar";
import LeftBar from "../components/shared/LeftBar";
import Bottombar from "../components/shared/BottomBar";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EZ Reality",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: [dark, shadesOfPurple ]
      }}
    >
      <html lang='en'>
        <body className={inter.className}>
          <TopBar />

          <main className='flex flex-row'>
            <LeftBar />
            <section className='main-container'>
              <div className='w-full max-w-4xl'>{children}</div>
            </section>
            {/* @ts-ignore */}
          </main>

          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
  );
}